
#   xero.project.toml
#   Comment shows the default

name    = "example"
entry   = "main.xe"
profile = "debug"

[profiles.debug]
opt_level = "o0"

[profiles.release]
opt_level = "o3"

[build]
path    = "build"
emit_ir = true

[diag]
print_tokens = false
print_ast    = false
