
#   xero.project.toml
#   Comment shows the default

name    = "example"
profile = "debug"
modules = [
    "main.xe",
    "math.xe"
]

[profiles.debug]
opt_level = "o0"        # "o0"

[profiles.release]
opt_level = "o3"

[build]
path    = "build"       # "build"
emit_ir = true          # true

[diag]
print_tokens = false    # false
print_ast    = false    # false
